// File generated by FlutterFire CLI.
// This file is used to configure Firebase for web.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

// For Firebase configuration, you would need to replace these values with your own
// Firebase project configuration (from Firebase console)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'create a new Firebase project and configure the options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'create a new Firebase project and configure the options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuration for web platform - replace with your Firebase web config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: 'mock-messaging-sender-id',
    projectId: 'mock-project-id',
    authDomain: 'mock-auth-domain',
    storageBucket: 'mock-storage-bucket',
    measurementId: 'mock-measurement-id',
  );

  // Configuration for Android platform - replace with your Firebase Android config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: 'mock-messaging-sender-id',
    projectId: 'mock-project-id',
    storageBucket: 'mock-storage-bucket',
  );

  // Configuration for iOS platform - replace with your Firebase iOS config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: 'mock-messaging-sender-id',
    projectId: 'mock-project-id',
    storageBucket: 'mock-storage-bucket',
    iosClientId: 'mock-ios-client-id',
    iosBundleId: 'mock-ios-bundle-id',
  );

  // Configuration for macOS platform - replace with your Firebase macOS config
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: 'mock-messaging-sender-id',
    projectId: 'mock-project-id',
    storageBucket: 'mock-storage-bucket',
    iosClientId: 'mock-ios-client-id',
    iosBundleId: 'mock-ios-bundle-id',
  );
} 